"""initial public schema

Revision ID: e79b07f88812
Revises: 
Create Date: 2026-09-24 00:14:51.125260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e79b07f88812'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_clerk_org_id'), 'tenants', ['clerk_org_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=True, schema='public')
    op.create_table('tenant_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_users_clerk_user_id'), 'tenant_users', ['clerk_user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False, schema='public')
    # NOTE: autogenerate also proposed `op.drop_table('alembic_version')` here -
    # that's Alembic's own bookkeeping table, mistakenly detected as "removed"
    # because it happens to live in the same `public` schema our models
    # target. Intentionally removed from this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_tenant_users_tenant_id'), table_name='tenant_users', schema='public')
    op.drop_index(op.f('ix_public_tenant_users_clerk_user_id'), table_name='tenant_users', schema='public')
    op.drop_table('tenant_users', schema='public')
    op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
    op.drop_index(op.f('ix_public_tenants_clerk_org_id'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    # ### end Alembic commands ###
