"""Official SAP Tax Number Categories reference list, extracted verbatim
from tax_cleansing_module.py::_SAP_TAX_CATEGORIES_SEED (source: SAP Help
'Tax Number Categories', User Guide SAP RDP). Used only for TAXTYPE
validation in Migration Preparation - never user-edited in the original
app (its Regelwerk tab only displays it, with a reset-to-official-list
button), so it lives here as a static constant rather than a DB table.

Extracted programmatically (ast.literal_eval) rather than retyped by
hand, for the same fidelity reason as fiscal_rules_seed.py.
"""

# (category_code, country_or_region_name, description)
SAP_TAX_CATEGORIES: list[tuple[str, str, str]] = [
    ('AD3', 'Andorra', 'Steuerregistrierungsnummer (NRT)'),
    ('AE0', 'VAE', 'Umsatzsteuer-Identifikationsnummer'),
    ('AE1', 'VAE', 'Steueridentifikationsnummer'),
    ('AF1', 'Afghanistan', 'Steueridentifikationsnummer'),
    ('AG1', 'Antigua und Barbuda', 'Umsatzsteuer-Identifikationsnummer'),
    ('AI3', 'Anguilla', 'Steueridentifikationsnummer'),
    ('AL1', 'Albanien', 'Umsatzsteuer-Identifikationsnummer'),
    ('AM1', 'Armenien', 'Umsatzsteuer-Identifikationsnummer'),
    ('AN1', 'Niederländische Antillen', 'Steueridentifikationsnummer'),
    ('AO3', 'Angola', 'Steueridentifikationsnummer (NIF)'),
    ('AQ1', 'Antarktis', 'Steueridentifikationsnummer'),
    ('AR1A', 'Argentinien', 'CUIT-Nummer'),
    ('AR1B', 'Argentinien', 'CUIL-Nummer'),
    ('AR1C', 'Argentinien', 'CDI-Nummer'),
    ('AR1D', 'Argentinien', 'DNI-Nummer'),
    ('AR1E', 'Argentinien', 'Ausländisches Ausweisdokument'),
    ('AR1F', 'Argentinien', 'Passnummer'),
    ('AR1Z', 'Argentinien', 'Ohne ID'),
    ('AR2', 'Argentinien', 'Einkommenssteuernummer'),
    ('AR3', 'Argentinien', 'NIP-Nummer oder CM-Nummer'),
    ('AS3', 'Samoa, Amerika', 'Steueridentifikationsnummer'),
    ('AT0', 'Österreich', 'Umsatzsteuer-Identifikationsnummer'),
    ('AU0', 'Australien', 'ABN'),
    ('AU1', 'Australien', 'Steueridentifikationsnummer (TFN)'),
    ('AU2', 'Australien', 'Australische Unternehmensnummer (ACN)'),
    ('AW3', 'Aruba', 'Steueridentifikationsnummer'),
    ('AZ3', 'Aserbaidschan', 'Steueridentifikationsnummer'),
    ('BA1', 'Bosnien-Herzegowina', 'Umsatzsteuer-Identifikationsnummer'),
    ('BB3', 'Barbados', 'Steueridentifikationsnummer'),
    ('BD1', 'Bangladesch', 'Umsatzsteuer-Identifikationsnummer'),
    ('BE0', 'Belgien', 'Umsatzsteuer-Identifikationsnummer'),
    ('BE1', 'Belgien', 'Unternehmensnummer'),
    ('BE2', 'Belgien', 'Umsatzsteuer-Identifikationsnummer ohne Länder-/Regionencode'),
    ('BE3', 'Belgien', 'Steueridentifikationsnummer'),
    ('BE4', 'Belgien', 'Gutschriftsnummer ERS'),
    ('BF3', 'Burkina Faso', 'Steueridentifikationsnummer'),
    ('BG0', 'Bulgarien', 'Umsatzsteuer-Identifikationsnummer'),
    ('BG1', 'Bulgarien', 'Einheitlicher ID-Code'),
    ('BG2', 'Bulgarien', 'Persönliche Identifikationsnummer'),
    ('BG3', 'Bulgarien', 'Sozialversicherungsnummer'),
    ('BH0', 'Bahrain', 'Umsatzsteuer-Identifikationsnummer'),
    ('BI3', 'Burundi', 'Steueridentifikationsnummer'),
    ('BJ3', 'Benin', 'Steueridentifikationsnummer'),
    ('BL1', 'Saint-Barthélemy', 'Steueridentifikationsnummer'),
    ('BM3', 'Bermuda', 'Steueridentifikationsnummer'),
    ('BN3', 'Brunei Darussalam', 'Steueridentifikationsnummer'),
    ('BO1', 'Bolivien', 'Steueridentifikationsnummer'),
    ('BQ3', 'Bonaire, Saba', 'Steueridentifikationsnummer'),
    ('BR1', 'Brasilien', 'CNPJ-Nummer'),
    ('BR2', 'Brasilien', 'CPF-Nummer'),
    ('BR3', 'Brasilien', 'Staatliche Steuernummer'),
    ('BR4', 'Brasilien', 'Kommunale Steuernummer'),
    ('BS1', 'Bahamas', 'Umsatzsteuer-Identifikationsnummer'),
    ('BT3', 'Bhutan', 'Steueridentifikationsnummer'),
    ('BW1', 'Botsuana', 'Umsatzsteuer-Identifikationsnummer'),
    ('BW5', 'Botsuana', 'Neue Umsatzsteuer-Identifikationsnummer'),
    ('BY1', 'Weißrussland', 'Umsatzsteuer-Identifikationsnummer'),
    ('BZ1', 'Belize', 'Sozialversicherungsnummer'),
    ('BZ2', 'Belize', 'Steuerkennung (freie Verwendung)'),
    ('BZ5', 'Belize', 'Steueridentifikationsnummer'),
    ('CA1', 'Kanada', 'Steuernummer für Lieferungen und Leistungen'),
    ('CA3', 'Kanada', 'Provinzumsatzsteuernummer (PST)'),
    ('CA4', 'Kanada', 'Harmonisierte Umsatzsteuernummer (HST)'),
    ('CC3', 'Kokosinseln', 'Steueridentifikationsnummer'),
    ('CD3', 'Demokratische Republik Kongo', 'Steueridentifikationsnummer'),
    ('CF3', 'Zentralafrikanische Republik', 'Steueridentifikationsnummer'),
    ('CG3', 'Republik Kongo', 'Steueridentifikationsnummer'),
    ('CH1', 'Schweiz', 'UID-Nummer'),
    ('CH2', 'Schweiz', 'Umsatzsteuer-Identifikationsnummer'),
    ('CI3', "Côte d'Ivoire", 'Steueridentifikationsnummer'),
    ('CK3', 'Cookinseln', 'Steueridentifikationsnummer'),
    ('CL1', 'Chile', 'RUT-Nummer'),
    ('CM3', 'Kamerun', 'Steueridentifikationsnummer'),
    ('CN0', 'China', 'Steuernummer (mappt auf CN5 in S/4HANA Public Cloud, vgl. SAP Note 3524568)'),
    ('CN5', 'China', 'Steuernummer'),
    ('CO1', 'Kolumbien', 'NIT-Nummer'),
    ('CO2', 'Kolumbien', 'Staatsangehörigkeitskarte'),
    ('CO3', 'Kolumbien', 'Einwandererausweis (älter als 18 Jahre)'),
    ('CO4', 'Kolumbien', 'Einwandererausweis (7 bis 18 Jahre alt)'),
    ('CO5', 'Kolumbien', 'Pass'),
    ('CR1', 'Costa Rica', 'Steuer'),
    ('CR3', 'Costa Rica', 'Steueridentifikationsnummer'),
    ('CS1', 'Serbien und Montenegro', 'Steueridentifikationsnummer'),
    ('CU3', 'Kuba', 'Steueridentifikationsnummer'),
    ('CV3', 'Kap Verde', 'Steueridentifikationsnummer'),
    ('CW3', 'Curaçao', 'Steueridentifikationsnummer'),
    ('CX3', 'Weihnachtsinsel', 'Steueridentifikationsnummer'),
    ('CY0', 'Zypern', 'Umsatzsteuer-Identifikationsnummer'),
    ('CY1', 'Zypern', 'Steueridentifikationscode (TIC)'),
    ('CZ0', 'Tschechische Republik', 'Umsatzsteuer-Identifikationsnummer'),
    ('CZ1', 'Tschechische Republik', 'DIC-Nummer'),
    ('CZ2', 'Tschechische Republik', 'ICO-Nummer'),
    ('DE0', 'Deutschland', 'Umsatzsteuer-Identifikationsnummer'),
    ('DE1', 'Deutschland', 'Steuernummer (z.B. für §48 EStG)'),
    ('DE2', '-', 'Obsolet'),
    ('DE3', '-', 'Obsolet'),
    ('DE4', '-', 'Obsolet'),
    ('DE5', '-', 'Obsolet'),
    ('DJ3', 'Dschibuti', 'Steueridentifikationsnummer'),
    ('DK0', 'Dänemark', 'Umsatzsteuer-Identifikationsnummer'),
    ('DK2', 'Dänemark', 'Steuernummer'),
    ('DM1', 'Dominica', 'Steueridentifikationsnummer'),
    ('DO1', 'Dominikanische Republik', 'RNC-Nummer'),
    ('DZ1', 'Algerien', 'NIF-Nummer'),
    ('EC3', 'Ecuador', 'Umsatzsteuer-Identifikationsnummer'),
    ('EE0', 'Estland', 'Umsatzsteuer-Identifikationsnummer'),
    ('EE1', 'Estland', 'Firmenregisternummer'),
    ('EG1', 'Ägypten', 'Steueridentifikationsnummer'),
    ('EG2', 'Ägypten', 'Steuerregistrierungsnummer'),
    ('EG3', 'Ägypten', 'Steueridentifikationsnummer'),
    ('EG4', 'Ägypten', 'Ausweisnummer'),
    ('ER1', 'Eritrea', 'Umsatzsteuer-Identifikationsnummer'),
    ('ES0', 'Spanien', 'Umsatzsteuer-Identifikationsnummer'),
    ('ES1', 'Spanien', 'NIF-Nummer'),
    ('ES2', 'Spanien', 'Nicht registriert'),
    ('ES4', 'Spanien', 'Gutschriftsnummer ERS'),
    ('ES5', 'Spanien', 'DIR3-Codes'),
    ('ET1', 'Äthiopien', 'Umsatzsteuer-Identifikationsnummer'),
    ('FI0', 'Finnland', 'Umsatzsteuer-Identifikationsnummer'),
    ('FI4', 'Finnland', 'Rechnungsnummer ERS'),
    ('FJ3', 'Fidschi', 'Umsatzsteuer-Identifikationsnummer'),
    ('FK3', 'Falklandinseln', 'Steueridentifikationsnummer'),
    ('FM3', 'Mikronesien', 'Steueridentifikationsnummer'),
    ('FO3', 'Färöer', 'Steueridentifikationsnummer'),
    ('FR0', 'Frankreich', 'Umsatzsteuer-Identifikationsnummer'),
    ('FR1', 'Frankreich', 'SIRET-Nummer'),
    ('FR2', 'Frankreich', 'SIREN-Nummer'),
    ('FR3', 'Frankreich', 'Steueridentifikationsnummer'),
    ('GA3', 'Gabun', 'Steueridentifikationsnummer'),
    ('GB0', 'Vereinigtes Königreich', 'Umsatzsteuer-Identifikationsnummer'),
    ('GB1', 'Vereinigtes Königreich', 'Passnummer'),
    ('GB2', 'Vereinigtes Königreich', 'Sozialversicherungsnummer'),
    ('GB3', 'Vereinigtes Königreich', 'Firmenregisternummer'),
    ('GB4', 'Vereinigtes Königreich', 'Eindeutige Steuerreferenz'),
    ('GB6', 'Protokoll zu Nordirland', 'Umsatzsteuer-Identifikationsnummer'),
    ('GD3', 'Grenada', 'Steueridentifikationsnummer'),
    ('GE3', 'Georgien', 'Steueridentifikationsnummer'),
    ('GG1', 'Guernsey', 'Steueridentifikationsnummer'),
    ('GH1', 'Ghana', 'Steueridentifikationsnummer'),
    ('GI3', 'Gibraltar', 'Steueridentifikationsnummer'),
    ('GL3', 'Grönland', 'Steueridentifikationsnummer'),
    ('GM3', 'Gambia', 'Steueridentifikationsnummer'),
    ('GN3', 'Guinea', 'Steueridentifikationsnummer'),
    ('GQ3', 'Äquatorialguinea', 'Steueridentifikationsnummer'),
    ('GR0', 'Griechenland', 'Umsatzsteuer-Identifikationsnummer'),
    ('GR1', 'Griechenland', 'Persönliche Identifikationsnummer'),
    ('GR2', 'Griechenland', 'AFM-Nummer'),
    ('GT1', 'Guatemala', 'Steueridentifikationsnummer'),
    ('GU1', 'Guam', 'Steueridentifikationsnummer'),
    ('GW3', 'Guinea-Bissau', 'Steueridentifikationsnummer'),
    ('GY3', 'Guyana', 'Steueridentifikationsnummer'),
    ('HK3', 'Hongkong', 'Handelsregisternummer'),
    ('HM3', 'Heard und McDonaldinseln', 'Steueridentifikationsnummer'),
    ('HN1', 'Honduras', 'Steueridentifikationsnummer'),
    ('HR0', 'Kroatien', 'Umsatzsteuer-Identifikationsnummer'),
    ('HR1', 'Kroatien', 'JMBG-Nummer'),
    ('HR2', 'Kroatien', 'OIB-Nummer'),
    ('HT3', 'Haiti', 'Steueridentifikationsnummer'),
    ('HU0', 'Ungarn', 'Umsatzsteuer-Identifikationsnummer'),
    ('HU1', 'Ungarn', 'Steuernummer'),
    ('HU3', 'Ungarn', 'Gruppensteuernummer'),
    ('HU4', 'Ungarn', 'Nummernkreis für Gutschriftsverfahren'),
    ('HU9', 'Ungarn', 'Nummernkreis für Abrechnung'),
    ('ID1', 'Indonesien', 'NPWP-Nummer'),
    ('ID3', 'Indonesien', 'NPPKP-Nummer'),
    ('IE0', 'Irland', 'Umsatzsteuer-Identifikationsnummer'),
    ('IE1', 'Irland', 'Firmenregisternummer'),
    ('IE2', 'Irland', 'Inländischer Lieferant ePWST'),
    ('IE5', 'Irland', 'Ausländischer Lieferant ePWST'),
    ('IL0', 'Israel', 'Umsatzsteuer-Identifikationsnummer'),
    ('IL1', 'Israel', 'Steuernummer 1'),
    ('IL2', 'Israel', 'Steuernummer 2'),
    ('IM0', 'Isle of Man', 'Umsatzsteuer-Identifikationsnummer'),
    ('IN2', 'Indien', 'Steueridentifikationsnummer'),
    ('IN3', 'Indien', 'Steuernummer für Lieferungen und Leistungen (GST-Identifikationsnummer)'),
    ('IN5', 'Indien', 'Steueridentifikationsnummer'),
    ('IO3', 'Britisches Territorium im Indischen Ozean', 'Steueridentifikationsnummer'),
    ('IQ3', 'Irak', 'Steueridentifikationsnummer'),
    ('IR3', 'Iran', 'Steueridentifikationsnummer'),
    ('IS3', 'Island', 'Identifikationsnummer'),
    ('IT0', 'Italien', 'Umsatzsteuer-Identifikationsnummer'),
    ('IT1', 'Italien', 'Codice Fiscale'),
    ('IT2', 'Italien', 'IVA-Code'),
    ('IT4', 'Italien', 'IPA-Code'),
    ('ITCF', 'Italien', 'Codice Fiscale'),
    ('JE3', 'Jersey', 'Steueridentifikationsnummer'),
    ('JM1', 'Jamaika', 'Steueridentifikationsnummer'),
    ('JO3', 'Jordanien', 'Steueridentifikationsnummer'),
    ('JP3', 'Japan', 'Unternehmensnummer'),
    ('JP4', 'Japan', 'Umsatzsteuer-Identifikationsnummer'),
    ('KE1', 'Kenia', 'Umsatzsteuer-Identifikationsnummer'),
    ('KE3', 'Kenia', 'PIN-Nummer'),
    ('KG1', 'Kirgisistan', 'Steueridentifikationsnummer'),
    ('KH1', 'Kambodscha', 'Steueridentifikationsnummer'),
    ('KI3', 'Kiribati', 'Steueridentifikationsnummer'),
    ('KM3', 'Komoren', 'Steueridentifikationsnummer'),
    ('KN3', 'St. Kitts und Nevis', 'Steueridentifikationsnummer'),
    ('KP3', 'Nordkorea', 'Handelsregisternummer'),
    ('KR1', 'Südkorea', 'Unternehmens- oder persönliche Identifikationsnummer'),
    ('KR2', 'Südkorea', 'Umsatzsteuer-Identifikationsnummer'),
    ('KW0', 'Kuwait', 'Umsatzsteuer-Identifikationsnummer'),
    ('KW1', 'Kuwait', 'Steueridentifikationsnummer'),
    ('KY1', 'Kaimaninseln', 'Umsatzsteuer-Identifikationsnummer'),
    ('KZ1', 'Kasachstan', 'RNN-Nummer'),
    ('LA1', 'Laos', 'Steueridentifikationsnummer'),
    ('LB1', 'Libanon', 'Steueridentifikationsnummer'),
    ('LC3', 'St. Lucia', 'Steueridentifikationsnummer'),
    ('LI1', 'Liechtenstein', 'Steueridentifikationsnummer'),
    ('LK3', 'Sri Lanka', 'Steueridentifikationsnummer'),
    ('LR1', 'Liberia', 'Steueridentifikationsnummer'),
    ('LS1', 'Lesotho', 'Umsatzsteuer-Identifikationsnummer'),
    ('LT0', 'Litauen', 'Umsatzsteuer-Identifikationsnummer'),
    ('LU0', 'Luxemburg', 'Umsatzsteuer-Identifikationsnummer'),
    ('LU1', 'Luxemburg', 'Steueridentifikationsnummer'),
    ('LV0', 'Lettland', 'Umsatzsteuer-Identifikationsnummer'),
    ('MA3', 'Marokko', 'Steueridentifikationsnummer'),
    ('MC0', 'Monaco', 'Umsatzsteuer-Identifikationsnummer'),
    ('MC1', 'Monaco', 'SIRET-Nummer'),
    ('MC2', 'Monaco', 'SIREN-Nummer'),
    ('MD1', 'Moldau', 'Steueridentifikationsnummer'),
    ('ME3', 'Montenegro', 'Steueridentifikationsnummer'),
    ('MG1', 'Madagaskar', 'Umsatzsteuer-Identifikationsnummer'),
    ('MH3', 'Marshallinseln', 'Steueridentifikationsnummer'),
    ('MK1', 'Nordmazedonien', 'Umsatzsteuer-Identifikationsnummer'),
    ('ML1', 'Mali', 'Steuernummer'),
    ('MM3', 'Myanmar', 'Steueridentifikationsnummer'),
    ('MN3', 'Mongolei', 'Steueridentifikationsnummer'),
    ('MO3', 'Macau', 'Steueridentifikationsnummer'),
    ('MP3', 'Nördliche Marianen', 'Steueridentifikationsnummer'),
    ('MR1', 'Mauretanien', 'Steueridentifikationsnummer'),
    ('MS3', 'Montserrat', 'Steueridentifikationsnummer'),
    ('MT0', 'Malta', 'Umsatzsteuer-Identifikationsnummer'),
    ('MU1', 'Mauritius', 'Steuerkontonummer (TAN)'),
    ('MU2', 'Mauritius', 'Handelsregisternummer'),
    ('MV3', 'Malediven', 'Steueridentifikationsnummer'),
    ('MW1', 'Malawi', 'Steueridentifikationsnummer'),
    ('MX1', 'Mexiko', 'RFC-Nummer'),
    ('MX2', 'Mexiko', 'Umsatzsteuerpflicht'),
    ('MX3', 'Mexiko', 'CURP-Nummer'),
    ('MY1', 'Malaysia', 'Steuernummer für Lieferungen und Leistungen'),
    ('MY2', 'Malaysia', 'Einkommenssteuernummer'),
    ('MY3', 'Malaysia', 'Dienstleistungssteuernummer'),
    ('MY4', 'Malaysia', 'Umsatzsteuerregistrierungsnummer'),
    ('MY5', 'Malaysia', 'Firmenregisternummer'),
    ('MY7', 'Malaysia', 'Steuernummer'),
    ('MZ1', 'Mosambik', 'Steuernummer (NUIT)'),
    ('NA1', 'Namibia', 'Umsatzsteuer-Identifikationsnummer'),
    ('NC3', 'Neukaledonien', 'Steueridentifikationsnummer'),
    ('NE3', 'Niger', 'Steueridentifikationsnummer'),
    ('NF3', 'Norfolkinsel', 'Steueridentifikationsnummer'),
    ('NG3', 'Nigeria', 'Steueridentifikationsnummer'),
    ('NG4', 'Nigeria', 'Umsatzsteuer-Identifikationsnummer'),
    ('NI3', 'Nicaragua', 'Steueridentifikationsnummer'),
    ('NL0', 'Niederlande', 'Umsatzsteuer-Identifikationsnummer'),
    ('NL1', 'Niederlande', 'Aansluitnummer UWV'),
    ('NL2', 'Niederlande', 'BSN-Nummer'),
    ('NL3', 'Niederlande', 'Loonbelastingnummer'),
    ('NL4', 'Niederlande', 'Vorherige Umsatzsteuer-Identifikationsnummer'),
    ('NO1', 'Norwegen', 'Umsatzsteuer-Identifikationsnummer'),
    ('NO2', 'Norwegen', 'Steuernummer'),
    ('NP1', 'Nepal', 'Umsatzsteuer-Identifikationsnummer'),
    ('NR3', 'Nauru', 'Steueridentifikationsnummer'),
    ('NU3', 'Niue', 'Steueridentifikationsnummer'),
    ('NZ1', 'Neuseeland', 'Steuernummer für Lieferungen und Leistungen'),
    ('NZ3', 'Neuseeland', 'NZBN-Nummer'),
    ('OM0', 'Oman', 'Umsatzsteuer-Identifikationsnummer'),
    ('OM1', 'Oman', 'Steueridentifikationsnummer'),
    ('PA3', 'Panama', 'RUC-Nummer'),
    ('PE1', 'Peru', 'RUC-Nummer'),
    ('PF3', 'Französisch-Polynesien', 'Steueridentifikationsnummer'),
    ('PG1', 'Papua-Neuguinea', 'Steueridentifikationsnummer'),
    ('PH1', 'Philippinen', 'Steueridentifikationsnummer'),
    ('PH3', 'Philippinen', 'Neue Steueridentifikationsnummer'),
    ('PK1', 'Pakistan', 'Steueridentifikationsnummer'),
    ('PL0', 'Polen', 'Umsatzsteuer-Identifikationsnummer'),
    ('PL1', 'Polen', 'NIP-Nummer'),
    ('PL2', 'Polen', 'PESEL-Nummer'),
    ('PM3', 'Saint-Pierre und Miquelon', 'Steueridentifikationsnummer'),
    ('PN3', 'Pitcairninseln', 'Steueridentifikationsnummer'),
    ('PR1', 'Puerto Rico', 'Steueridentifikationsnummer'),
    ('PS1', 'Palästina', 'Steueridentifikationsnummer'),
    ('PT0', 'Portugal', 'Umsatzsteuer-Identifikationsnummer'),
    ('PT1', 'Portugal', 'NIF-Nummer'),
    ('PW3', 'Palau', 'Steueridentifikationsnummer'),
    ('PY3', 'Paraguay', 'Steueridentifikationsnummer'),
    ('QA0', 'Katar', 'Umsatzsteuer-Identifikationsnummer'),
    ('QA1', 'Katar', 'Steueridentifikationsnummer'),
    ('RO0', 'Rumänien', 'Umsatzsteuer-Identifikationsnummer'),
    ('RO1', 'Rumänien', 'Steuernummer'),
    ('RO3', 'Rumänien', 'Persönliche Identifikationsnummer'),
    ('RO5', 'Rumänien', 'Steuernummer zugeordnet zu STCD5'),
    ('RS1', 'Serbien', 'JMBG-Nummer oder PIB-Nummer'),
    ('RS2', 'Serbien', 'Identifikationsnummer'),
    ('RU1', 'Russland', 'INN'),
    ('RU2', 'Russland', 'OKPO-Code'),
    ('RU3', 'Russland', 'KPP-Nummer'),
    ('RU4', 'Russland', 'OFK-Nummer'),
    ('RW1', 'Ruanda', 'Umsatzsteuer-Identifikationsnummer'),
    ('SA0', 'Saudi-Arabien', 'Umsatzsteuer-Identifikationsnummer'),
    ('SA1', 'Saudi-Arabien', 'Steueridentifikationsnummer'),
    ('SB3', 'Salomonen', 'Steueridentifikationsnummer'),
    ('SC1', 'Seychellen', 'Steueridentifikationsnummer'),
    ('SD3', 'Sudan', 'Steueridentifikationsnummer'),
    ('SE0', 'Schweden', 'Umsatzsteuer-Identifikationsnummer'),
    ('SE2', 'Schweden', 'Unternehmensidentifikationsnummer'),
    ('SG1', 'Singapur', 'Steuernummer für Lieferungen und Leistungen'),
    ('SG2', 'Singapur', 'NRIC/FIN-Nummer'),
    ('SG3', 'Singapur', 'Eindeutige Entitätsnummer (UEN)'),
    ('SH3', 'St. Helena', 'Steueridentifikationsnummer'),
    ('SI0', 'Slowenien', 'Umsatzsteuer-Identifikationsnummer'),
    ('SI1', 'Slowenien', 'Steuernummer'),
    ('SK0', 'Slowakei', 'Umsatzsteuer-Identifikationsnummer'),
    ('SK1', 'Slowakei', 'DIC-Nummer'),
    ('SK2', 'Slowakei', 'ICO-Nummer'),
    ('SL5', 'Sierra Leone', 'Umsatzsteuer-Identifikationsnummer'),
    ('SM0', 'San Marino', 'Umsatzsteuer-Identifikationsnummer'),
    ('SN3', 'Senegal', 'NINEA-Nummer'),
    ('SO3', 'Somalia', 'Steueridentifikationsnummer'),
    ('SR1', 'Suriname', 'Steueridentifikationsnummer'),
    ('SS3', 'Südsudan', 'Steueridentifikationsnummer'),
    ('ST3', 'São Tomé und Príncipe', 'Steueridentifikationsnummer'),
    ('SV1', 'El Salvador', 'Steueridentifikationsnummer'),
    ('SX3', 'Sint Maarten', 'Steueridentifikationsnummer'),
    ('SY3', 'Syrien', 'Steueridentifikationsnummer'),
    ('SZ1', 'Swasiland', 'Steueridentifikationsnummer'),
    ('TC3', 'Turks- und Caicosinseln', 'Steueridentifikationsnummer'),
    ('TD3', 'Tschad', 'Steueridentifikationsnummer'),
    ('TF3', 'Französische Südgebiete', 'Steueridentifikationsnummer'),
    ('TG3', 'Togo', 'Steueridentifikationsnummer'),
    ('TH1', 'Thailand', 'Persönliche Identifikationsnummer'),
    ('TH2', 'Thailand', 'Steuer-ID'),
    ('TH3', 'Thailand', 'Steuer-ID'),
    ('TJ1', 'Tadschikistan', 'Umsatzsteuer-Identifikationsnummer'),
    ('TK1', 'Tokelau', 'Steueridentifikationsnummer'),
    ('TL3', 'Osttimor', 'Steueridentifikationsnummer'),
    ('TM3', 'Turkmenistan', 'Steueridentifikationsnummer'),
    ('TN1', 'Tunesien', 'Umsatzsteuer-Identifikationsnummer'),
    ('TO3', 'Tonga', 'Steueridentifikationsnummer'),
    ('TR1', 'Türkei', 'Finanzamt'),
    ('TR2', 'Türkei', 'Steuernummer'),
    ('TT1', 'Trinidad und Tobago', 'Steueridentifikationsnummer'),
    ('TV3', 'Tuvalu', 'Steueridentifikationsnummer'),
    ('TW1', 'Taiwan', 'Registriernummer GUI'),
    ('TW2', 'Taiwan', 'Steuerregistrierungsnummer'),
    ('TZ1', 'Tansania', 'Umsatzsteuer-Identifikationsnummer'),
    ('TZ3', 'Tansania', 'Steueridentifikationsnummer'),
    ('UA1', 'Ukraine', 'Individual Tax Number'),
    ('UA2', 'Ukraine', 'Taxpayer Tax Number/SRNP Number'),
    ('UA3', 'Ukraine', 'VAT Registration Number'),
    ('UG1', 'Uganda', 'Steueridentifikationsnummer'),
    ('UG3', 'Uganda', 'Umsatzsteuer-Identifikationsnummer'),
    ('UM1', 'United States Minor Outlying Islands', 'Umsatzsteuer-Identifikationsnummer'),
    ('US01', 'USA', 'Steueridentifikationsnummer'),
    ('US1', 'USA', 'Sozialversicherungsnummer'),
    ('US2', 'USA', 'Arbeitgeber-Identifikationsnummer'),
    ('US4', 'USA', 'Eindeutige Formularidentifikationsnummer'),
    ('US5', 'USA', 'GIIN-Nummer'),
    ('UY3', 'Uruguay', 'RUT-Nummer'),
    ('UZ1', 'Usbekistan', 'Steueridentifikationsnummer'),
    ('VA3', 'Vatikanstadt', 'Steueridentifikationsnummer'),
    ('VC3', 'St. Vincent', 'Steueridentifikationsnummer'),
    ('VE1', 'Venezuela', 'RIF-Nummer'),
    ('VE2', 'Venezuela', 'NIT-Nummer'),
    ('VG1', 'Britische Jungferninseln', 'Umsatzsteuer-Identifikationsnummer'),
    ('VI3', 'Amerikanische Jungferninseln', 'Steueridentifikationsnummer'),
    ('VN1', 'Vietnam', 'Steueridentifikationsnummer'),
    ('VU3', 'Vanuatu', 'Steueridentifikationsnummer'),
    ('WF3', 'Wallis und Futuna', 'Steueridentifikationsnummer'),
    ('WS3', 'Samoa', 'Steueridentifikationsnummer'),
    ('YE3', 'Jemen', 'Steueridentifikationsnummer'),
    ('YT3', 'Mayotte', 'Steueridentifikationsnummer'),
    ('ZA1', 'Südafrika', 'Umsatzsteuer-Identifikationsnummer'),
    ('ZA3', 'Südafrika', 'Einkommenssteueridentifikationsnummer'),
    ('ZA5', 'Südafrika', 'Steuerregistrierungsnummer'),
    ('ZM1', 'Sambia', 'Steueridentifikationsnummer'),
    ('ZW1', 'Simbabwe', 'Umsatzsteuer-Identifikationsnummer'),
    ('ZW2', 'Simbabwe', 'Geschäftspartnernummer (BPN)'),
]

OBSOLETE_CATEGORIES: set[str] = {'DE2', 'DE3', 'DE4', 'DE5'}
